---
title: "hill-function-sample"
author: "Nobuaki Masaki"
date: "21 August 2019"
output: html_document
---

```{r}
library(tidyverse)
library(data.table)
library(parallel)
setwd("Hill_Stationary_Correct//n_6")

calculate_error_hill <- function(x_y_df_stationary, n, K, x_bar, x2_bar, x3_bar) {
  
  xyn_yn_Kn_bar <- sum(x_y_df_stationary$x*x_y_df_stationary$y^n/(x_y_df_stationary$y^n+K^n)*x_y_df_stationary$t)/sum(x_y_df_stationary$t)
  x2yn_yn_Kn_bar <- sum(x_y_df_stationary$x^2*x_y_df_stationary$y^n/(x_y_df_stationary$y^n+K^n)*x_y_df_stationary$t)/sum(x_y_df_stationary$t)
  yn_yn_Kn_bar <- sum(x_y_df_stationary$y^n/(x_y_df_stationary$y^n+K^n)*x_y_df_stationary$t)/sum(x_y_df_stationary$t)
  
  cov_XY <- xyn_yn_Kn_bar - x_bar*yn_yn_Kn_bar

  lhs_AB <- xyn_yn_Kn_bar/yn_yn_Kn_bar + 1
  rhs_AB <- x2_bar/x_bar
  
  error_AB <- 2*(lhs_AB-rhs_AB)/(lhs_AB+rhs_AB)
  
  lhs_BC <- x2yn_yn_Kn_bar/yn_yn_Kn_bar + 2*x2_bar + xyn_yn_Kn_bar/yn_yn_Kn_bar + x2_bar/x_bar
  rhs_BC <- x3_bar/x_bar + 2*xyn_yn_Kn_bar/yn_yn_Kn_bar*x_bar + 2*x_bar
  
  error_BC <- 2*(lhs_BC-rhs_BC)/(lhs_BC+rhs_BC)
  
  lhs_CA <- xyn_yn_Kn_bar/yn_yn_Kn_bar + x2_bar/x_bar + x2yn_yn_Kn_bar/yn_yn_Kn_bar
  rhs_CA <- x3_bar/x_bar
  
  error_CA <- 2*(lhs_CA-rhs_CA)/(lhs_CA+rhs_CA)

  return(list(error_AB, error_BC, error_CA, cov_XY))
}

calculate_error_iter_hill_sample <- function(design_matrix, x_y_df_stationary, intended_x_bar, intended_y_bar, intended_gamma, intended_true_n, intended_true_K, samp_size) {
    
  n <- design_matrix$n
  K <- design_matrix$K
  seed <- design_matrix$index
  
  x_y_df_stationary_ <- x_y_df_stationary %>% 
    filter(x_bar == intended_x_bar & y_bar == intended_y_bar & gamma == intended_gamma & true_n == intended_true_n & true_K == intended_true_K)

  sumt <- sum(x_y_df_stationary_$t)
  x_y_df_stationary_$t <- x_y_df_stationary_$t/sumt

  samp <- mod_sample(seq(nrow(x_y_df_stationary_)), samp_size, replace = T, x_y_df_stationary_$t, seed)
  x <- x_y_df_stationary_$x[samp]
  y <- x_y_df_stationary_$y[samp]
  sample <- as.data.frame(cbind(x, y))
  colnames(sample) <- c("x", "y")
  sample$t <- 1
  sumt <- nrow(sample)
  sample <- sample %>% 
    group_by(x,y) %>%
    summarize(t = sum(t)/sumt)
  x_bar <- sum(sample$x*sample$t)/sum(sample$t)
  x2_bar <- sum(sample$x^2*sample$t)/sum(sample$t)
  x3_bar <- sum(sample$x^3*sample$t)/sum(sample$t)
  
  error <- calculate_error_hill(sample, n, K, x_bar, x2_bar, x3_bar)
  
  return(error)
}

mod_sample <- function(x, size, replace, prob, seed) {
  set.seed(seed)
  return(sample(x, size, replace, prob))
}

hill_tbl <- 
    list.files(pattern = "*.csv") %>% 
    map_df(~fread(.))

colnames(hill_tbl) <- c("x", "y", "t", "x_bar", "y_bar", "gamma", "true_n", "true_K")
```

```{r}
index <- seq(1000)
n <- seq(1, 10, 0.1)
K <- seq(10, 100, 1)

design_matrix <- merge(index, n, by = NULL) %>%
  merge(K, by = NULL)

colnames(design_matrix) <- c("index", "n", "K")
 
d_ <- list()
    
for (i in seq(nrow(design_matrix))) {
     l <- as.list(design_matrix[i,])
     d_[[i]] <- l
}

set.seed(17)
error <- lapply(d_, calculate_error_iter_hill_sample, x_y_df_stationary = hill_tbl, intended_x_bar = 10, intended_y_bar = 10, intended_gamma = 0.1, intended_true_n = 6, intended_true_K = 30, samp_size = 500)

error <- t(matrix(unlist(error), nrow=length(unlist(error[1]))))
design_matrix <- design_matrix %>% mutate(error_AB = error[ ,1], error_BC = error[,2])
```


```{r}
setwd("C:\\Users\\Nobua\\Documents\\FUSRP")
#write.csv(design_matrix, "hill-function-sample.csv", row.names = FALSE)
design_matrix <- read.csv("hill-function-sample_50_50_0.1_5_70_10-4_30.csv")

#ggplot(design_matrix, aes(n,K,z = error_BC)) + geom_contour(aes(colour = stat(level))) + facet_wrap(vars(index)) + scale_color_gradient2() + theme_dark() + geom_vline(xintercept = 3) + geom_hline(yintercept = 75)

design_matrix_line_AB <- design_matrix %>%
  mutate(error = abs(error_AB)) %>%
  group_by(n, index) %>%
  filter(error == min(error, na.rm = TRUE)) %>%
  mutate(line = "Variance Invariant") %>%
  select(n, K, error, line, index) %>%
  filter(K < 100)

design_matrix_line_BC <- design_matrix %>%
  mutate(error = abs(error_BC)) %>%
  group_by(n, index) %>%
  filter(error == min(error, na.rm = TRUE)) %>%
  mutate(line = "Skewness Invariant") %>%
  select(n, K, error, line, index) %>%
  filter(K < 100)

design_matrix_lines_inner <- inner_join(design_matrix_line_AB, design_matrix_line_BC, by = c("n", "K", "index"))

design_matrix_lines <- rbind(design_matrix_line_AB, design_matrix_line_BC)

ggplot(design_matrix_lines_inner, aes(x = n, y = K, group = index)) + geom_tile(alpha = 1) + geom_vline(xintercept = 5) + geom_hline(yintercept = 70) + scale_x_continuous(breaks = seq(0,20)) + labs(title = "Variance Invariant for N = 500", x = "Tested n", y = "Tested K") + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5))

length(unique(design_matrix_lines_inner$index))

ggplot(design_matrix_lines, aes(x = n, y = K, fill = line)) + geom_tile(alpha = 0.1) + geom_vline(xintercept = 5) + geom_hline(yintercept = 70) + scale_x_continuous(breaks = seq(0,20)) + labs(title = TeX("Variance Invariant for $N = 10^4$"), x = "Tested n", y = "Tested K") + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5))

ggplot(design_matrix_lines, aes(x = n, y = K, fill = line)) + geom_tile() + geom_vline(xintercept = 3) + geom_hline(yintercept = 75) + scale_x_continuous(breaks = seq(0,20)) + labs(title = TeX("$10^4$"), x = "Tested n", y = "Tested K") + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) + facet_wrap(vars(index))
```

```{r}
design_matrix <- read.csv("hill-function-sample_50_50_0.1_5_70_10-3_30.csv")

#ggplot(design_matrix, aes(n,K,z = error_BC)) + geom_contour(aes(colour = stat(level))) + facet_wrap(vars(index)) + scale_color_gradient2() + theme_dark() + geom_vline(xintercept = 3) + geom_hline(yintercept = 75)

design_matrix_line_AB <- design_matrix %>%
  mutate(error = abs(error_AB)) %>%
  group_by(n, index) %>%
  filter(error == min(error, na.rm = TRUE)) %>%
  mutate(line = "Variance") %>%
  select(n, K, error, line, index) %>%
  filter(K < 100)

design_matrix_line_BC <- design_matrix %>%
  mutate(error = abs(error_BC)) %>%
  group_by(n, index) %>%
  filter(error == min(error, na.rm = TRUE)) %>%
  mutate(line = "Skewness") %>%
  select(n, K, error, line, index) %>%
  filter(K < 100)

design_matrix_lines_inner <- inner_join(design_matrix_line_AB, design_matrix_line_BC, by = c("n", "K", "index"))

design_matrix_lines <- rbind(design_matrix_line_AB, design_matrix_line_BC)

ggplot(design_matrix_lines_inner, aes(x = n, y = K, group = index)) + geom_tile(alpha = 1, fill = "purple") + geom_vline(xintercept = 5) + geom_hline(yintercept = 70) + labs(title = TeX("Sampled Intersection Points from Invariants ($N = 10^3$)"), x = "Tested n", y = "Tested K", caption = TeX("$n^* = 5$, $K^* = 70$,  $<x_1> = 50$, $<x_2> = 50$, $\\beta_1 = 0.1$")) + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) + xlim(4,8) + ylim(50, 100)

length(unique(design_matrix_lines_inner$index))

design_matrix_lines$line <- factor(design_matrix_lines$line, c("Variance", "Skewness"))

p2 <- ggplot(design_matrix_lines, aes(x = n, y = K, fill = line)) + geom_tile(alpha = 0.1)+ scale_fill_manual(values = c("red", "blue"), name = "Invariant") + scale_x_continuous(breaks = seq(0,20)) + labs(title = TeX("Sampled Minimum Error from Invariants ($N = 10^3$)"), x = "Tested n", y = "Tested K", caption = TeX("$n^* = 5$, $K^* = 70$,  $<x_1> = 50$, $<x_2> = 50$, $\\beta_1 = 0.1$")) + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5), legend.position="bottom") + geom_hline(yintercept = 70) + geom_vline(xintercept = 5)

p2
```

```{r}
hill <- function(y,n,K) {
  return((y^n/(y^n + K^n))*(50^12/(50^12 + 80^12))/(50^n/(50^n + K^n)))
}

Generate_Poisson <- function(x_bar, x_max) {
   x <- seq(0, x_max)
   x <- as.data.frame(x)
   x$t <- x_bar^x$x*exp(-x_bar)/factorial(x$x)
   return(x)
}

y <- 0:100
y <- as.data.frame(y)
  
design_matrix_lines_inner$setting <- seq(81)  
  
design_matrix_lines_inner %>% merge(y, all = TRUE) -> design_matrix_error_inner

design_matrix_error_inner %>% mutate(hill = hill(y = y, n = n, K = K)) -> hill_plot_AB

hill_plot_AB <- design_matrix_error_inner %>% mutate(hill = hill(y = y, n = n, K = K))

a <- ggplot(hill_plot_AB, aes(x = y, y = log(hill), color = factor(setting))) + geom_line(alpha = 0.5) + labs(title = "Hill Functions From Overlapping Region", x = TeX("$x_1$"), y = TeX("$log(f(x_1))$")) + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5), legend.position = "none")

poisson_AB <- Generate_Poisson(50, 100)

b <- ggplot(poisson_AB) + aes(x = x, y = t) + geom_bar(stat = "identity") + labs(title = TeX("Distribution of $x_1$"), x = TeX("x_1"), y = "Mass") + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) + xlim(0, 100)

gA <- ggplotGrob(a)
gB <- ggplotGrob(b)
maxWidth = grid::unit.pmax(gA$widths[2:5], gB$widths[2:5])
gA$widths[2:5] <- as.list(maxWidth)
gB$widths[2:5] <- as.list(maxWidth)
gridExtra::grid.arrange(gB, gA, ncol=1)
```

