---
title: "hill-function-statistics"
author: "Nobuaki Masaki"
date: "5 August 2019"
output: html_document
---

```{r}
library(tidyverse)
library(data.table)
library(parallel)
setwd("hill_stationary_distros")

calculate_error_hill <- function(x_y_df_stationary, n, K, x_bar, x2_bar, x3_bar) {
  
  xyn_yn_Kn_bar <- sum(x_y_df_stationary$x*x_y_df_stationary$y^n/(x_y_df_stationary$y^n+K^n)*x_y_df_stationary$t)/sum(x_y_df_stationary$t)
  x2yn_yn_Kn_bar <- sum(x_y_df_stationary$x^2*x_y_df_stationary$y^n/(x_y_df_stationary$y^n+K^n)*x_y_df_stationary$t)/sum(x_y_df_stationary$t)
  yn_yn_Kn_bar <- sum(x_y_df_stationary$y^n/(x_y_df_stationary$y^n+K^n)*x_y_df_stationary$t)/sum(x_y_df_stationary$t)

  lhs_AB <- xyn_yn_Kn_bar/yn_yn_Kn_bar + 1
  rhs_AB <- x2_bar/x_bar
  
  error_AB <- 2*(lhs_AB-rhs_AB)/(lhs_AB+rhs_AB)
  
  lhs_BC <- x2yn_yn_Kn_bar/yn_yn_Kn_bar + 2*x2_bar + xyn_yn_Kn_bar/yn_yn_Kn_bar + x2_bar/x_bar
  rhs_BC <- x3_bar/x_bar + 2*xyn_yn_Kn_bar/yn_yn_Kn_bar*x_bar + 2*x_bar
  
  error_BC <- 2*(lhs_BC-rhs_BC)/(lhs_BC+rhs_BC)

  return(list(error_AB, error_BC))
}

calculate_error_iter_hill <- function(design_matrix, x_y_df_stationary, x_bar, x2_bar, x3_bar) {
    
  n <- design_matrix$n
  K <- design_matrix$K
  
  error <- calculate_error_hill(x_y_df_stationary, n, K, x_bar, x2_bar, x3_bar)
  
  return(error)
}

Generate_Poisson <- function(x_bar, x_max) {
   x <- seq(0, x_max)
   x <- as.data.frame(x)
   x$t <- dpois(x$x, x_bar, log = FALSE)
   return(x)
}

KLD <- function(x_y_df_stationary) {
  x_y_df_stationary <- x_y_df_stationary %>%
    group_by(x) %>%
    summarize(t = sum(t)) %>%
    mutate(t = t/sum(t))
  x_bar <- sum(x_y_df_stationary$x*x_y_df_stationary$t)/sum(x_y_df_stationary$t)
  x_max <- max(x_y_df_stationary$x)
  poisson <- Generate_Poisson(x_bar, x_max)
  d_ <- left_join(x_y_df_stationary, poisson, by = "x")
  colnames(d_) <- c("x", "t1", "t2")
  #d_<-d_[(d_$t2>0),]
  #d_<-d_[d_$t2>0.000000000000000000001,]
  KLD <- sum(d_$t1*log(d_$t1/d_$t2))
  return(KLD)
}

BC <- function(x_y_df_stationary) {
  x_y_df_stationary <- x_y_df_stationary %>%
    group_by(x) %>%
    summarize(t = sum(t)) %>%
    mutate(t = t/sum(t))
  x_bar <- sum(x_y_df_stationary$x*x_y_df_stationary$t)/sum(x_y_df_stationary$t)
  x_max <- max(x_y_df_stationary$x)
  poisson <- Generate_Poisson(x_bar, x_max)
  d_ <- left_join(x_y_df_stationary, poisson, by = "x")
  colnames(d_) <- c("x", "t1", "t2")
  BC <- sum(sqrt(d_$t1*d_$t2))
  return(BC)
}

Fc <- function(sta){
  x_bar <- sum(sta$x*sta$t)/sum(sta$t)
  R_plus <- sum(sta$R_plus*sta$t)/sum(sta$t)
  R_minus <- sum(sta$R_minus*sta$t)/sum(sta$t)
  eta_xR_plus <- (sum(sta$x*sta$R_plus*sta$t)/sum(sta$t) - x_bar*R_plus)/x_bar/R_plus
  Fc <- eta_xR_plus/(1/x_bar + eta_xR_plus)
  return(Fc)
}

gradient_hill <- function(design_matrix, true_n, true_K) {
  n_plus <- design_matrix %>% filter(n < true_n + 0.10001 & n > true_n + 0.09999 & K == true_K)
  n_minus <- design_matrix %>% filter(n < true_n - 0.09999 & n > true_n - 0.10001 & K == true_K)
  K_plus <- design_matrix %>% filter(n == true_n & K == true_K + 1)
  K_minus <- design_matrix %>% filter(n == true_n & K == true_K - 1)
  
  derrorAB_dn <- (n_plus$error_AB - n_minus$error_AB)/0.2
  derrorBC_dn <- (n_plus$error_BC - n_minus$error_BC)/0.2
  
  derrorAB_dK <- (K_plus$error_AB - K_minus$error_AB)/2
  derrorBC_dK <- (K_plus$error_BC - K_minus$error_BC)/2
  
  # gradient_AB <- sqrt(derrorAB_dn^2 + derrorAB_dK^2)
  # gradient_BC <- sqrt(derrorBC_dn^2 + derrorBC_dK^2)
  # 
  # cos_similarity <- (derrorAB_dn*derrorBC_dn + derrorAB_dK*derrorBC_dK)/sqrt(derrorAB_dn^2 + derrorAB_dK^2)/sqrt(derrorBC_dn^2 + derrorBC_dK^2)
  
  return(list(derrorAB_dn, derrorBC_dn, derrorAB_dK, derrorBC_dK))
}

calculate_error_hill_batch <- function(sta, x_bar, x2_bar, x3_bar, n, K) {

  KLD <- KLD(sta)
  BC <- BC(sta)
  Fc <- Fc(sta)
  
  n_list <- c(n - 0.1, n, n + 0.1)
  K_list <- c(K - 1, K, K + 1)
  
  design_matrix <- n_list %>%
      merge(K_list, by = NULL)
  colnames(design_matrix) <- c("n", "K")
  design_matrix <- as.data.frame(design_matrix)
    
  d_ <- list()
  for (i in seq(nrow(design_matrix))) {
    l <- as.list(design_matrix[i,])
    d_[[i]] <- l
  }
  
  error <- lapply(d_, calculate_error_iter_hill, 
                x_y_df_stationary = sta, 
                x_bar = x_bar, 
                x2_bar = x2_bar, 
                x3_bar = x3_bar)
  
  error_ABC <- t(matrix(unlist(error), nrow=length(unlist(error[1]))))
  design_matrix$error_AB <- error_ABC[ ,1]
  design_matrix$error_BC <- error_ABC[ ,2]
  
  gradient_list <- gradient_hill(design_matrix, n, K)
  gradient <- t(matrix(unlist(gradient_list), nrow=length(unlist(gradient_list[1]))))
  derrorAB_dn <- gradient[[1]]
  derrorBC_dn <- gradient[[2]]
  derrorAB_dK <- gradient[[3]]
  derrorBC_dK <- gradient[[4]]
  
  return(list(KLD, BC, Fc, derrorAB_dn, derrorBC_dn, derrorAB_dK, derrorBC_dK, x_bar))
}

calculate_error_iter_hill_batch <- function(design_matrix, x_y_df_stationary) {
    
  intended_x_bar <- design_matrix$x_bar
  intended_y_bar <- design_matrix$y_bar
  intended_gamma <- design_matrix$gamma
  intended_true_n <- design_matrix$true_n
  intended_true_K <- design_matrix$true_K
  
  x_y_df_stationary_ <- x_y_df_stationary %>% 
    filter(x_bar == intended_x_bar & y_bar == intended_y_bar & gamma == intended_gamma & true_n == intended_true_n & true_K == intended_true_K)
  
  x_bar <- sum(x_y_df_stationary_$x*x_y_df_stationary_$t)/sum(x_y_df_stationary_$t)
  x2_bar <- sum(x_y_df_stationary_$x^2*x_y_df_stationary_$t)/sum(x_y_df_stationary_$t)
  x3_bar <- sum(x_y_df_stationary_$x^3*x_y_df_stationary_$t)/sum(x_y_df_stationary_$t)
  
  d_ <- calculate_error_hill_batch(x_y_df_stationary_, x_bar, x2_bar, x3_bar, intended_true_n, intended_true_K)
  
  return(d_)
}

hill_tbl <- 
    list.files(pattern = "*.csv") %>% 
    map_df(~fread(.))

colnames(hill_tbl) <- c("x", "y", "t", "x_bar", "y_bar", "gamma", "true_n", "true_K")
```

```{r}
design_matrix <- hill_tbl %>% 
  group_by(x_bar, y_bar, gamma, true_n, true_K) %>% 
  filter(row_number() == 1) %>%
  select(x_bar, y_bar, gamma, true_n, true_K)

colnames(design_matrix) <- c("x_bar", "y_bar", "gamma", "true_n", "true_K")

#design_matrix <- design_matrix[1:2,]

d_ <- list()
    
for (i in seq(nrow(design_matrix))) {
     l <- as.list(design_matrix[i,])
     d_[[i]] <- l
}

set.seed(17)
stats_ <- lapply(d_, calculate_error_iter_hill_batch, x_y_df_stationary = hill_tbl)
stats_ <- t(matrix(unlist(stats_), nrow=length(unlist(stats_[1]))))

design_matrix$KLD <- stats_[ ,1]
design_matrix$BC <- stats_[,2]
design_matrix$Fc <- stats_[,3]
design_matrix$derrorAB_dn <- stats_[,4]
design_matrix$derrorBC_dn <- stats_[,5]
design_matrix$derrorAB_dK <- stats_[,6]
design_matrix$derrorBC_dK <- stats_[,7]
design_matrix$emp_x_bar <- stats_[,8]
```

```{r}
design_matrix2 <- design_matrix %>% filter(gamma == 1 & true_n < 4) 
ggplot(design_matrix2, aes(true_n, true_K, fill = derrorAB_dK)) + geom_tile() + facet_grid(x_bar ~ y_bar)
```






```{r}
setwd("C:\\Users\\Nobua\\Documents\\FUSRP")
hill_tbl2 <- hill_tbl %>% filter(x_bar == 50 & y_bar == 50 & gamma == 1 & true_n == 3 & true_K == 75)

write.csv(hill_tbl2, "test_hill.csv")
```




```{r}
true_n_list <- seq(1,12,1)
true_K_list <- seq(10,150,10)
true_lambda_list <- c(1, 5, 10)
true_x_bar_list <- c(10, 50, 100)

design_matrix_2 <- merge(true_n_list, true_K_list, by = NULL) %>%
    merge(true_lambda_list, by = NULL) %>%
    merge(true_x_bar_list, by = NULL)

colnames(design_matrix_2) <- c("n", "K", "lambda", "adj_x_bar")
design_matrix_2 <- as.data.frame(design_matrix_2)

d2_ <- list()
    
for (i in seq(nrow(design_matrix_2))) {
     l <- as.list(design_matrix_2[i,])
     d2_[[i]] <- l
}

set.seed(17)
d_ <- mclapply(d2_, calculate_error_iter_hill_batch, N = 1000000, alpha = 10e+10, beta = 0.05, gamma = 0.1, mc.cores = 19)

d_gradients <- t(matrix(unlist(d_), nrow=length(unlist(d_[1]))))
design_matrix_2$KLD <- d_gradients[ ,1]
design_matrix_2$BC <- d_gradients[ ,2]
design_matrix_2$Fc <- d_gradients[ ,3]
design_matrix_2$h <- d_gradients[ ,4]
design_matrix_2$eta_x_R_plus <- d_gradients[ ,5]
design_matrix_2$derrorAB_dn <- d_gradients[ ,6]
design_matrix_2$derrorBC_dn <- d_gradients[ ,7]
design_matrix_2$derrorAB_dK <- d_gradients[ ,8]
design_matrix_2$derrorBC_dK <- d_gradients[ ,9]
design_matrix_2$x_bar <- d_gradients[ ,10]
```

```{r}
write.csv(design_matrix_2, "hill-function-statistics.csv", row.names = FALSE)
```

```{r}
#analysis starts here
Hill <- read.csv("hill-function-stats.csv")

Hill$derrorAB_dK <- 10*Hill$derrorAB_dK
Hill$derrorBC_dK <- 10*Hill$derrorBC_dK

Hill$norm_AB <- sqrt(Hill$derrorAB_dn^2 + Hill$derrorAB_dK^2)
Hill$norm_BC <- sqrt(Hill$derrorBC_dn^2 + Hill$derrorBC_dK^2)

Hill$cos_similarity <- (Hill$derrorAB_dn*Hill$derrorBC_dn + Hill$derrorAB_dK*Hill$derrorBC_dK)/(Hill$norm_AB*Hill$norm_BC)

Hill$adj_x_bar_factor <- as.factor(Hill$adj_x_bar)
Hill$adj_x_bar_factor <- revalue(Hill$adj_x_bar_factor, c("10"="mean of x = 10", "50"="mean of x = 50", "100"="mean of x = 100"))

Hill$adj_y_bar_factor <- as.factor(Hill$lambda)
Hill$adj_y_bar_factor <- revalue(Hill$adj_y_bar_factor, c("1"="mean of y = 10", "5"="mean of y = 50", "10"="mean of y = 100"))

Hill1 <- Hill %>% filter(lambda == 1)
Hill2 <- Hill %>% filter(lambda == 5)
Hill3 <- Hill %>% filter(lambda == 10)

p1 <- ggplot(Hill, aes(n, K, fill = log(derrorAB_dn + 0.001))) + geom_tile() + facet_grid(vars(adj_y_bar_factor), vars(adj_x_bar_factor)) + labs(x = TeX("$n^*$"), y = TeX("$K^*$")) + theme_bw() + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) + scale_fill_continuous(name=TeX("$\\log{(\\frac{\\partial E2(n^*, K^*)}{\\partial n})}$"))

p2 <- ggplot(Hill2, aes(n, K, fill = derrorAB_dn)) + geom_tile() + facet_grid(vars(adj_y_bar_factor), vars(adj_x_bar_factor)) + labs(x = TeX("$n^*$"), y = TeX("$K^*$")) + theme_bw() + theme(text = element_text(size=20), plot.title = element_text(hjust = 0.5)) + scale_fill_continuous(name=TeX("$\\frac{\\partial E2(n^*, K^*)}{\\partial n}$"))  

grid.arrange(p1, p2, nrow = 2)
p1
p3 <- ggplot(Hill3, aes(n, K, fill = derrorAB_dn)) + geom_tile() + facet_grid(vars(adj_y_bar_factor), vars(adj_x_bar_factor)) + labs(x = TeX("$n^*$"), y = TeX("$K^*$")) + theme_bw() + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) + scale_fill_continuous(name=TeX("$\\frac{\\partial E2(n^*, K^*)}{\\partial n}$"))

ggplot(Hill, aes(Fc, norm_BC)) + geom_point() + facet_grid(vars(adj_y_bar_factor), vars(adj_x_bar_factor), scales = "free") + labs(x = TeX("$F_c$"), y = TeX("$||\\nabla E3||$")) + theme_bw() + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) + scale_fill_continuous(name=TeX("$\\log{(\\frac{\\partial E3(n^*, K^*)}{\\partial n})}$"))

ggplot(Hill2, aes(n, K, fill = derrorAB_dK)) + geom_tile() + facet_grid(vars(adj_y_bar_factor), vars(adj_x_bar_factor)) + labs(x = TeX("$n^*$"), y = TeX("$K^*$")) + theme_bw() + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) + scale_fill_continuous(name=TeX("$\\frac{\\partial E2(n^*, K^*)}{\\partial K}$"))

ggplot(Hill3, aes(n, K, fill = derrorAB_dK)) + geom_tile() + facet_grid(vars(adj_y_bar_factor), vars(adj_x_bar_factor)) + labs(x = TeX("$n^*$"), y = TeX("$K^*$")) + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) + scale_fill_continuous(name=TeX("$\\frac{\\partial E2(n^*, K^*)}{\\partial K}$"))

ggplot(Hill2, aes(n, K, fill = derrorBC_dn)) + geom_tile() + facet_grid(vars(adj_y_bar_factor), vars(adj_x_bar_factor)) + labs(x = TeX("$n^*$"), y = TeX("$K^*$")) + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) + scale_fill_continuous(name=TeX("$\\frac{\\partial E3(n^*, K^*)}{\\partial n}$"))

ggplot(Hill2, aes(n, K, fill = derrorBC_dK)) + geom_tile() + facet_grid(vars(adj_y_bar_factor), vars(adj_x_bar_factor)) + labs(x = TeX("$n^*$"), y = TeX("$K^*$")) + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) + scale_fill_continuous(name=TeX("$\\frac{\\partial E3(n^*, K^*)}{\\partial K}$"))

ggplot(Hill2, aes(n, K, fill = derrorBC_dK)) + geom_tile() + facet_grid(vars(adj_y_bar_factor), vars(adj_x_bar_factor)) + labs(x = TeX("$n^*$"), y = TeX("$K^*$")) + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) + scale_fill_continuous(name=TeX("$\\frac{\\partial E3(n^*, K^*)}{\\partial K}$"))

Hill5 <- Hill2

Hill5$cos_similarity <- ifelse(Hill2$n >= 5 & Hill2$K >= 50, Hill2$cos_similarity, NA)

ggplot(Hill2, aes(n, K, fill = norm_AB)) + geom_tile() + facet_grid(vars(adj_y_bar_factor), vars(adj_x_bar_factor)) + labs(x = TeX("$n^*$"), y = TeX("$K^*$")) + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) + scale_fill_continuous(name=TeX("$||\\nabla E2||$"))

ggplot(Hill5, aes(n, K, fill = cos_similarity)) + geom_tile() + facet_grid(vars(adj_y_bar_factor), vars(adj_x_bar_factor)) + labs(x = TeX("$n^*$"), y = TeX("$K^*$")) + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) + scale_fill_continuous(name=TeX("$\\cos{\\theta}$"))

ggplot(Hill2, aes(Fc, norm_AB)) + geom_point() + facet_grid(vars(adj_y_bar_factor), vars(adj_x_bar_factor)) + labs(x = TeX("$F_c$"), y = TeX("$||\\nabla E2||$")) + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) 

ggplot(Hill2, aes(Fc, norm_BC)) + geom_point() + facet_grid(vars(adj_y_bar_factor), vars(adj_x_bar_factor)) + labs(x = TeX("$F_c$"), y = TeX("$||\\nabla E3||$")) + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) 

ggplot(Hill2, aes(KLD, BC)) + geom_point() + facet_grid(vars(adj_y_bar_factor), vars(adj_x_bar_factor)) + labs(x = TeX("$KLD$"), y = TeX("$BC$")) + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) 


ggplot(Hill, aes(norm_AB)) + geom_tile() + facet_grid(vars(adj_y_bar_factor), vars(adj_x_bar_factor)) + labs(x = TeX("$n^*$"), y = TeX("$K^*$")) + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) + scale_fill_continuous(name=TeX("$\\cos{\\theta}$"))
```

```{r}
ggplot(Hill, aes(n, cos_similarity)) + geom_boxplot() + facet_grid(vars(adj_y_bar_factor), vars(adj_x_bar_factor))
```

```{r}
design_matrix <- read.csv("K_80_n_20.csv")
cutoff_error_AB <- 0.01
cutoff_error_BC <- 0.01

design_matrix_error_AB <- design_matrix %>%
  mutate(error = abs(error_AB)) %>%
  filter(error <= cutoff_error_AB) %>%
  mutate(line = "Variance Invariant") %>%
  select(n, K, error, line)

design_matrix_error_BC <- design_matrix %>%
  mutate(error = abs(error_BC)) %>%
  filter(error <= cutoff_error_BC) %>%
  mutate(line = "Skewness Invariant") %>%
  select(n, K, error, line)

design_matrix_error <- rbind(design_matrix_error_AB, design_matrix_error_BC)

design_matrix_error_2 <- inner_join(design_matrix_error_AB, design_matrix_error_BC, by = c("n", "K"))

design_matrix_error_3 <- left_join(design_matrix_error, design_matrix_error_2, by = c("n", "K")) 

design_matrix_error_3$line <- ifelse(is.na(design_matrix_error_3$line.x), design_matrix_error_3$line, "Overlap")

design_matrix_error_3$line <- factor(design_matrix_error_3$line, levels = c("Variance Invariant", "Skewness Invariant", "Overlap"))

p2 <- ggplot(design_matrix_error_3, aes(x = n, y = K, fill = line)) + geom_tile() + scale_fill_manual(values = c("red", "blue", "purple"), name = "Regions") + scale_x_continuous(breaks = seq(0,30)) + labs(title = "Regions of Minimum Error from Invariants", x = "Tested n", y = "Tested K", caption = "Variance Invariant Error = 0.02, Skewness Invariant Error = 0.05") + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5)) + geom_hline(yintercept = 30) + geom_vline(xintercept = 12)

p2
```

```{r}
design_matrix_error_AB <- design_matrix %>%
  mutate(error = abs(error_AB)) %>%
  filter(error <= 0.0005) %>%
  mutate(line = "Variance Invariant") %>%
  select(n, K, error, line)

p2 <- ggplot(design_matrix_error_AB, aes(x = n, y = K, fill = error)) + geom_tile() + scale_x_continuous(breaks = seq(0,30)) + labs(title = "Regions of Minimum Error from Invariants", x = "Tested n", y = "Tested K", caption = "Variance Invariant Error = 0.02, Skewness Invariant Error = 0.05") + theme(text = element_text(size=20), axis.text.x = element_text(angle=90, hjust=1), plot.title = element_text(hjust = 0.5))
p2
```



