---
title: "mass-action-batch"
author: "Nobuaki Masaki"
date: "20 August 2019"
output: html_document
---

```{r}
library(tidyverse)
library(data.table)
library(parallel)
setwd("MA_stationary_distros")

calculate_error_MA <- function(x_y_df_stationary, n, x_bar, x2_bar, x3_bar) {
  
  var_x <- x2_bar - x_bar^2
  xyn_bar <- sum(x_y_df_stationary$x*x_y_df_stationary$y^n*x_y_df_stationary$t)/sum(x_y_df_stationary$t)
  x2yn_bar <- sum(x_y_df_stationary$x^2*x_y_df_stationary$y^n*x_y_df_stationary$t)/sum(x_y_df_stationary$t)
  yn_bar <- sum(x_y_df_stationary$y^n*x_y_df_stationary$t)/sum(x_y_df_stationary$t)
  cov_x_yn <- xyn_bar - x_bar*yn_bar
  cov_x2_yn <- x2yn_bar - x2_bar*yn_bar
  cov_x2_x <- x3_bar - x2_bar*x_bar

  lhs_AB <- 1/x_bar + cov_x_yn/x_bar/yn_bar
  rhs_AB <- var_x/x_bar^2
  
  error_AB <- 2*(lhs_AB-rhs_AB)/(lhs_AB+rhs_AB)
  
  lhs_BC <- cov_x_yn/x_bar/yn_bar + cov_x2_x/2/x_bar^3
  rhs_BC <- var_x/x_bar^2 + (cov_x2_yn + cov_x_yn)/2/x_bar^2/yn_bar + var_x/2/x_bar^3 
    
  error_BC <- 2*(lhs_BC-rhs_BC)/(lhs_BC+rhs_BC)

  return(list(error_AB, error_BC))
}

calculate_error_iter_MA <- function(design_matrix, x_y_df_stationary) {
  
  intended_x_bar <- design_matrix$x_bar
  intended_y_bar <- design_matrix$y_bar
  intended_gamma <- design_matrix$gamma
  intended_true_n <- design_matrix$true_n
  n <- design_matrix$n
  
  x_y_df_stationary_ <- x_y_df_stationary %>% 
    filter(x_bar == intended_x_bar & y_bar == intended_y_bar & gamma == intended_gamma & true_n == intended_true_n)
  
  x_bar <- sum(x_y_df_stationary_$x*x_y_df_stationary_$t)/sum(x_y_df_stationary_$t)
  x2_bar <- sum(x_y_df_stationary_$x^2*x_y_df_stationary_$t)/sum(x_y_df_stationary_$t)
  x3_bar <- sum(x_y_df_stationary_$x^3*x_y_df_stationary_$t)/sum(x_y_df_stationary_$t)
  
  error <- calculate_error_MA(x_y_df_stationary_, n, x_bar, x2_bar, x3_bar)
  
  return(error)
}

MA_tbl <- 
    list.files(pattern = "*.csv") %>% 
    map_df(~fread(.))

colnames(MA_tbl) <- c("x", "y", "t", "x_bar", "y_bar", "gamma", "true_n")
```

```{r}
n <- seq(0, 6, 0.1)

design_matrix <- MA_tbl %>% 
  group_by(x_bar, y_bar, gamma, true_n) %>% 
  filter(row_number() == 1) %>%
  select(x_bar, y_bar, gamma, true_n) %>%
  merge(n, by = NULL)

colnames(design_matrix) <- c("x_bar", "y_bar", "gamma", "true_n", "n")

#design_matrix <- design_matrix[1:2,] testing
 
d_ <- list()
    
for (i in seq(nrow(design_matrix))) {
     l <- as.list(design_matrix[i,])
     d_[[i]] <- l
}

set.seed(17)
error <- lapply(d_, calculate_error_iter_MA, x_y_df_stationary = MA_tbl)
error <- t(matrix(unlist(error), nrow=length(unlist(error[1]))))
design_matrix <- design_matrix %>% mutate(error_AB = error[ ,1], error_BC = error[,2])
```

```{r}
library(latex2exp)
setwd("C:\\Users\\Nobua\\Documents\\FUSRP")
#write.csv(design_matrix, "mass-action-batch.csv")

design_matrix <- read.csv("mass-action-batch.csv")
design_matrix$true_n <- factor(design_matrix$true_n)
levels(design_matrix$true_n) <- c("n = 1", "n = 2", "n = 3", "n = 4")

ma_batch_0 <- design_matrix %>% filter(x_bar == 50 & y_bar == 50 & gamma == 1)

a <- ggplot(ma_batch_0, aes(x = n, y = error_AB, color = as.factor(true_n))) + geom_line() + scale_color_discrete(name = "") + geom_hline(yintercept = 0) + labs(x = "Tested Exponent n", y = "Variance Invariant Error", caption = TeX("$<x_1> = 50$, $<x_2> = 50$, $\\beta_1 = 1$"), tag = "A") + theme_bw() + theme(text = element_text(size=15))

ma_batch_1 <- design_matrix %>% filter(x_bar == 50 & y_bar == 50)

b <- ggplot(ma_batch_1, aes(x = n, y = error_AB, color = as.factor(gamma))) + geom_line() + scale_color_discrete(name = TeX("$\\beta_1$")) + facet_wrap(vars(true_n)) + geom_hline(yintercept = 0) + labs(x = "Tested Exponent n", y = "Variance Invariant Error", caption = TeX("$<x_1> = 50$, $<x_2> = 50$"), tag = "B") + theme_bw() + theme(text = element_text(size=15))

ma_batch_2 <- design_matrix %>% filter(y_bar == 50 & gamma == 1)

c <- ggplot(ma_batch_2, aes(x = n, y = error_AB, color = as.factor(x_bar))) + geom_line() + scale_color_discrete(name = "<x_2>") + facet_wrap(vars(true_n)) + geom_hline(yintercept = 0) + labs(x = "Tested Exponent n", y = "Variance Invariant Error", caption = TeX("$<x_1> = 50$, $\\beta = 1$"), tag = "C") + theme_bw() + theme(text = element_text(size=15))

ma_batch_3 <- design_matrix %>% filter(x_bar == 50 & gamma == 1)

d <- ggplot(ma_batch_3, aes(x = n, y = error_AB, color = as.factor(y_bar))) + geom_line() + scale_color_discrete(name = TeX("$<x_1>$")) + facet_wrap(vars(true_n)) + geom_hline(yintercept = 0) + labs(x = "Tested Exponent n", y = "Variance Invariant Error", caption = TeX("$<x_2> = 50$, $\\beta_1 = 1$"), tag = "D") + theme_bw() + theme(text = element_text(size=15))

gridExtra::grid.arrange(a,b,c,d,nrow=2)
```

```{r}
#if x2 -> x1
setwd("MA_stationary_distros")

MA_tbl <- 
    list.files(pattern = "*.csv") %>% 
    map_df(~fread(.))

colnames(MA_tbl) <- c("y", "x", "t", "y_bar", "x_bar", "gamma", "true_n")

n <- seq(-1, 3, 0.1)
x_bar <- 50
y_bar <- 50
gamma <- 1
true_n <- 2

design_matrix <- as.data.frame(cbind(n, x_bar, y_bar, gamma, true_n))

d_ <- list()
    
for (i in seq(nrow(design_matrix))) {
     l <- as.list(design_matrix[i,])
     d_[[i]] <- l
}

set.seed(17)
error <- lapply(d_, calculate_error_iter_MA, x_y_df_stationary = MA_tbl)
error <- t(matrix(unlist(error), nrow=length(unlist(error[1]))))
design_matrix <- design_matrix %>% mutate(error_AB = error[ ,1], error_BC = error[,2])
```

```{r}
ggplot(design_matrix, aes(n, error_AB)) + geom_line() + geom_hline(yintercept = 0) + geom_vline(xintercept = 0) + labs(title = TeX("If $x_2 \\rightarrow x_1$"), x = "Tested Exponent n", y = "Variance Invariant Error", caption = TeX("$<x_1> = 50$, $<x_2> = 50$, $\\beta_1 = 1$, $n = 2$")) + theme_bw() + theme(text = element_text(size=20), plot.title = element_text(hjust = 0.5))
```

```{r}
#n = 0
setwd("n_0")
MA_tbl <- 
    list.files(pattern = "*.csv") %>% 
    map_df(~fread(.))

colnames(MA_tbl) <- c("x", "y", "t", "x_bar", "y_bar", "gamma", "true_n")

n <- seq(-1, 6, 0.1)
x_bar <- 50
y_bar <- 50
gamma <- 0.1
true_n <- 0

design_matrix <- as.data.frame(cbind(n, x_bar, y_bar, gamma, true_n))

d_ <- list()
    
for (i in seq(nrow(design_matrix))) {
     l <- as.list(design_matrix[i,])
     d_[[i]] <- l
}

set.seed(17)
error <- lapply(d_, calculate_error_iter_MA, x_y_df_stationary = MA_tbl)
error <- t(matrix(unlist(error), nrow=length(unlist(error[1]))))
design_matrix <- design_matrix %>% mutate(error_AB = error[ ,1], error_BC = error[,2])
```

```{r}
ggplot(design_matrix, aes(n, error_AB)) + geom_line() + labs(title = "n = 0", x = "Tested Exponent n", y = "Variance Invariant Error", caption = TeX("$<x_1> = 50$, $<x_2> = 50$, $\\beta_1 = 1$")) + theme_bw() + theme(text = element_text(size=20), plot.title = element_text(hjust = 0.5)) + ylim(-1, 1)
```


